### PR TITLE
Update gc-stats to fix node 10 install issues

### LINKED ISSUE #48: Outdated node-gcstats causes install problems in node 10
I found issues when installing this package in node 10 and with lerna.
This package has as optional dependency`gc-stats` which was the origin of this problem with a outdated `node-pre-gyp` .
For more information please look at https://github.com/dainis/node-gcstats/issues/31 and https://github.com/dainis/node-gcstats/issues/33

The `gc-stats` package is now bumped to `v1.2.1` which resolves all these issues.

### PR DESCRIPTION
**Pull request by fernandopasik**
fixes #48

### CODE REVIEW

**Comment by fernandopasik** [comment]
@SimenB would it be possible to merge this?

**Comment by SimenB** [comment]
Sorry, missed this!

**Comment by SimenB** [comment]
>`prometheus-gc-stats 0.6.1 published 🎉`

**Comment by fernandopasik** [comment]
Thank you @SimenB !

**Pull request merged**
